# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybelt_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poked_by', to='pybelt_app.User')),
                ('poker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poked', to='pybelt_app.User')),
            ],
        ),
    ]
